---

sap_anydb_install_oracle_prep_reboot_ok: yes

sap_anydb_install_oracle_prep_fail_if_reboot_required: no

sap_anydb_install_oracle_prep_precheck: no

# minimal, responsefile
sap_anydb_install_oracle_method: minimal

#sap_anydb_install_oracle_sid: OR1

sap_anydb_install_oracle_base: /oracle

sap_anydb_install_oracle_filesystem_storage: /oradata

sap_anydb_install_oracle_inventory_central: /oraInventory

sap_anydb_install_oracle_system_password:

sap_anydb_install_oracle_extract_path: # e.g. /software


folder_to_run_hana_installation_from: "/sap-installation/hana-installation"

oracle_zip_file: 51053828.ZIP
oracle_zip_folder: "/sapmnt/software/ORACLE_DB_Software"
oracle_unarchived_folder: "/sap-installation/oracle-installation/unarchived"
oracle_file_full_path: "{{ oracle_zip_folder }}/{{ oracle_zip_file }}"

hana_installation_file_path: "{{ hana_unarchived_folder }}/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm"
hana_passwords_file_full_path: "{{ hana_unarchived_folder }}/passwords.xml"
hana_instance_number: "{{ HANA_INSTANCE_NUMBER }}"

sap_install_error: "There was an error on your SAP installation. Please check the output and the logs"
standard_sap_install_error_msg: "Configuration error (batch mode):\n  SAP HANA System ID '{{ GLOBAL_HANA_SID }}' is already in use by a SAP HANA Database instance!"

already_installed_error_message: "SAP HANA System ID '{{ GLOBAL_HANA_SID }}' is already in use by a SAP HANA Database instance!"
