---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Variables to check disks mounted
regex_to_look_for_disks: "nvme\\w*n1\\b"
#when xvd format
#regex_to_look_for_disks: "xvd\\w*\\b"
minimum_number_of_mounted_disks_to_search: 14

grep_find_command: grep /dev/xvd
awk_position_command: awk '{ print $18 }'
sed_replace_command: sed -e 's/"//g' -e 's/\.*//g'

sapmnt_folder: /sapmnt

main_root_mount: /mnt/efs

disk_mapping_file_full_path: /tmp/diskmap

efs_folders_to_create:
  - /mnt/efs/ASCS00
  - /mnt/efs/ERS10
  - /mnt/efs/sapmnt
  - /mnt/efs/trans

folders_to_create:
  - /oracle
  - /oracle/{{ GLOBAL_SAP_SID }}/sapdata1
  - /oracle/{{ GLOBAL_SAP_SID }}/sapdata2
  - /oracle/{{ GLOBAL_SAP_SID }}/sapdata3
  - /oracle/{{ GLOBAL_SAP_SID }}/sapdata4
  - /oracle/{{ GLOBAL_SAP_SID }}/origlogA
  - /oracle/{{ GLOBAL_SAP_SID }}/origlogA
  - /oracle/{{ GLOBAL_SAP_SID }}/origlogB
  - /oracle/{{ GLOBAL_SAP_SID }}/mirrlogA
  - /oracle/{{ GLOBAL_SAP_SID }}/mirrlogB
  - /usr/sap
#  - /hana/shared
#  - /hana/data
#  - /hana/log
# - /usr/sap/trans
#  - /software
#  - /backup
folders_to_create_with_difrrent_permission:
  - /oracle/{{ GLOBAL_SAP_SID }}
  - /oracle/{{ GLOBAL_SAP_SID }}/oraarch


# Variables for mounting ORACLE disks
oracle_folder: /oracle
volume_group_oracle: vg_oracle
logical_volume_oracle: lv_oracle

oracle_disk_type_pattern:
  - nvme1n1

# Variables for mounting ORACLE/GLOBAL_SAP_SID disks
oracle_folder_GLOBAL_SAP_SID: /oracle/{{ GLOBAL_SAP_SID }}
volume_group_oracle_GLOBAL_SAP_SID: vg_oracle_GLOBAL_SAP_SID
logical_volume_oracle_GLOBAL_SAP_SID: lv_oracle_GLOBAL_SAP_SID

oracle_disk_type_pattern_GLOBAL_SAP_SID:
  - nvme2n1

# Variables for mounting ORACLE/oraarch disks
oracle_folder_oraarch: /oracle/{{ GLOBAL_SAP_SID }}/oraarch
volume_group_oracle_GLOBAL_SAP_SID_oraarch: vg_oracle_GLOBAL_SAP_SID_oraarch
logical_volume_oracle_GLOBAL_SAP_SID_oraarch: lv_oracle_GLOBAL_SAP_SID_oraarch

oracle_disk_type_pattern_orarch:
  - nvme3n1 

# Variables for mounting DATA disks
oracle_data1_folder: /oracle/{{ GLOBAL_SAP_SID }}/sapdata1
oracle_data2_folder: /oracle/{{ GLOBAL_SAP_SID }}/sapdata2
oracle_data3_folder: /oracle/{{ GLOBAL_SAP_SID }}/sapdata3
oracle_data4_folder: /oracle/{{ GLOBAL_SAP_SID }}/sapdata4
volume_group_oracle_data1: vg_oracle_data1
volume_group_oracle_data2: vg_oracle_data2
volume_group_oracle_data3: vg_oracle_data3
volume_group_oracle_data4: vg_oracle_data4
logical_volume_oracle_data1: lv_oracle_data1
logical_volume_oracle_data2: lv_oracle_data2
logical_volume_oracle_data3: lv_oracle_data3
logical_volume_oracle_data4: lv_oracle_data4
#hana_data_folder: /hana/data
#volume_group_hana_data: vg_hana_data
#logical_volume_hana_data: lv_hana_data

oracle_data_disk_type_pattern_data:
  - nvme4n1
  - nvme5n1
  - nvme6n1
  - nvme7n1

# Variables for mounting LOG disks
oracle_orig_logA_folder: /oracle/{{ GLOBAL_SAP_SID }}/origlogA
oracle_orig_logB_folder: /oracle/{{ GLOBAL_SAP_SID }}/origlogB
oracle_mirr_logA_folder: /oracle/{{ GLOBAL_SAP_SID }}/mirrlogA
oracle_mirr_logB_folder: /oracle/{{ GLOBAL_SAP_SID }}/mirrlogB
volume_group_oracle_orig_logA: vg_oracle_orig_logA
volume_group_oracle_orig_logB: vg_oracle_orig_logB
volume_group_oracle_mirr_logA: vg_oracle_mirr_logA
volume_group_oracle_mirr_logB: vg_oracle_mirr_logB
logical_volume_oracle_orig_logA: lv_oracle_orig_logA
logical_volume_oracle_orig_logB: lv_oracle_orig_logB
logical_volume_oracle_mirr_logA: lv_oracle_mirr_logA
logical_volume_oracle_mirr_logB: lv_oracle_mirr_logB

#hana_log_folder: /hana/log
#volume_group_hana_log: vg_hana_log
#logical_volume_hana_log: lv_hana_log

oracle_log_disk_type_pattern_log:
  - nvme8n1
  - nvme9n1
  - nvme10n1
  - nvme11n1

# Variables for mounting SAP disks
oracle_sap_folder: /usr/sap
volume_group_oracle_sap: vg_usrsap
logical_volume_oracle_sap: lv_usrsap

oracle_sap_disk_type_pattern_usr_sap:
  - nvme12n1

# Variables for mounting SHARED disks
#hana_shared_folder: /hana/shared
#volume_group_hana_shared: vg_hana_shared
#logical_volume_hana_shared: lv_hana_shared

#hana_shared_disk_type_pattern:
#  - xvdo

# Variables for mounting SAP disks
#hana_sap_folder: /usr/sap
#volume_group_hana_sap: vg_usrsap
#logical_volume_hana_sap: lv_usrsap

#hana_sap_disk_type_pattern:
#  - xvdq

# Variables for mounting BACKUP disks
#hana_backup_folder: /backup
#volume_group_hana_backup: vg_hana_backup
#logical_volume_hana_backup: lv_hana_backup

#hana_backup_disk_type_pattern:
#  - xvdp

# Variables for mounting SWAP disks
#hana_swap: /swap
#volume_group_hana_swap: vg_swap
#logical_volume_hana_swap: lv_swap

#hana_swap_disk_type_pattern:
#  - xvdr
